# Generated by Django 4.1.7 on 2023-03-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "NewsTitle",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                ("NewsBody", models.TextField(verbose_name="Текст блога")),
                (
                    "NewsDatePosted",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "NewsPhoto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/%Y/%m/%d",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-NewsDatePosted"],
            },
        ),
    ]
