# Generated by Django 4.1.7 on 2023-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="NewsBody",
            field=models.TextField(verbose_name="Текст новости"),
        ),
    ]
