# Generated by Django 4.1.7 on 2023-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_newsbody"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="NewsAnonce",
            field=models.CharField(max_length=100, null=False, verbose_name="Анонс"),
        ),
    ]
