# Generated by Django 4.1.7 on 2023-03-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptions", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "О нас",
                "verbose_name_plural": "О нас",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CityName",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название города",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ["CityName"],
            },
        ),
        migrations.CreateModel(
            name="LinksTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TelegramIcon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="TelegramIcon",
                        verbose_name="Иконка Telegram",
                    ),
                ),
                (
                    "TelegramLink",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ссылка на Telegram",
                    ),
                ),
                (
                    "WhatsappIcon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="WhatsappIcon",
                        verbose_name="Иконка Whatsapp",
                    ),
                ),
                (
                    "WhatsappLink",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ссылка на Whatsapp",
                    ),
                ),
                (
                    "VKIcon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="VKIcon",
                        verbose_name="Иконка VK",
                    ),
                ),
                (
                    "VKLink",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ссылка на VK",
                    ),
                ),
                (
                    "ViberIcon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ViberIcon",
                        verbose_name="Иконка Viber",
                    ),
                ),
                (
                    "ViberLink",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ссылка на Viber",
                    ),
                ),
                (
                    "TwoGisIcon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="TwoGisIcon",
                        verbose_name="Иконка 2Gis",
                    ),
                ),
                (
                    "TwoGisLink",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ссылка на 2Gis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на соцсети",
                "verbose_name_plural": "Ссылки на соцсети",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LogoSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="LogoSite",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="favicon",
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Логотип",
                "verbose_name_plural": "Логотипы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MainIndexAdditionService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Услуги доп услуги",
                "verbose_name_plural": "Услуги доп услуги",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MainIndexChapterOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Услуги левая колонка",
                "verbose_name_plural": "Услуги левая колонка",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MainIndexChapterTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Услуги правая колонка",
                "verbose_name_plural": "Услуги правая колонка",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MainIndexMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="MainPageMedia",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуги Фото",
                "verbose_name_plural": "Услуги Фото",
            },
        ),
        migrations.CreateModel(
            name="Technics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TechnicName",
                    models.CharField(
                        max_length=100, verbose_name="Наименование техники"
                    ),
                ),
            ],
            options={
                "verbose_name": "Техника",
                "verbose_name_plural": "Техника",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserFirstName", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "UserLastName",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
                ("UserPhone", models.CharField(max_length=100, verbose_name="Телефон")),
                ("UserAddress", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "UserIntercomCode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Код домофона",
                    ),
                ),
                (
                    "UserEmail",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "UserCityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cities",
                        verbose_name="Ссылка на город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["UserCityId"],
            },
        ),
        migrations.CreateModel(
            name="UsersReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField(verbose_name="Отзыв")),
                (
                    "ReviewDate",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата отзыва"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.users",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "OwnerFirstName",
                    models.CharField(max_length=100, verbose_name="Имя"),
                ),
                (
                    "OwnerLastName",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                (
                    "OwnerPhone",
                    models.CharField(max_length=100, verbose_name="Телефон"),
                ),
                (
                    "OwnerEmail",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "OwnerLegalAddress",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "OwnerCityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cities",
                        verbose_name="Ссылка на город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Владелец",
                "verbose_name_plural": "Владельцы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "OrderDescriptions",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Описание поломки",
                    ),
                ),
                (
                    "OrderDate",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
                (
                    "OrderTechnicsId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.technics",
                        verbose_name="Ссылка на технику",
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.users",
                        verbose_name="Ссылка на пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-OrderDate"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BlogsTitle",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                ("BlogsBody", models.TextField(verbose_name="Текст блога")),
                (
                    "BlogsDatePosted",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "BlogsPhoto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/%Y/%m/%d",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "BlogsAuthor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.owner",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-BlogsDatePosted"],
            },
        ),
    ]
