# Generated by Django 4.1.7 on 2023-03-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-NewsDatePosted"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.RenameField(
            model_name="news",
            old_name="BlogsAuthor",
            new_name="NewsAuthor",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="BlogsBody",
            new_name="NewsBody",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="BlogsDatePosted",
            new_name="NewsDatePosted",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="BlogsPhoto",
            new_name="NewsPhoto",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="BlogsTitle",
            new_name="NewsTitle",
        ),
    ]
