# Generated by Django 4.1.7 on 2023-03-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_news_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="NewsAuthor",
        ),
    ]
