# Generated by Django 4.1.7 on 2023-03-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LinksTable",
        ),
        migrations.DeleteModel(
            name="LogoSite",
        ),
        migrations.DeleteModel(
            name="MainIndexAdditionService",
        ),
        migrations.DeleteModel(
            name="MainIndexMedia",
        ),
    ]
